// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShopProject.Infrastructure.Data;

#nullable disable

namespace PetShopProject.Infrastructure.Migrations
{
    [DbContext(typeof(PetShopDbContext))]
    [Migration("20240411190347_AddPropertyQuantityToProductEntityAdd500Quantity")]
    partial class AddPropertyQuantityToProductEntityAdd500Quantity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Address identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasComment("City for registration");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasComment("Postal code for registration");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Street for registration");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasComment("Address entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sofia",
                            PostalCode = "1000",
                            Street = "ul. Lelin"
                        });
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Blog post identifuer");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Author identifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Content of blog post");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date time of publishing blog post");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Title of a blog post");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("BlogPosts");

                    b.HasComment("Blog post of a user");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.BlogPostTag", b =>
                {
                    b.Property<int>("BlogPostId")
                        .HasColumnType("int")
                        .HasComment("Post identifier");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasComment("Tag identifier");

                    b.Property<int?>("BlogPostTagBlogPostId")
                        .HasColumnType("int");

                    b.Property<int?>("BlogPostTagTagId")
                        .HasColumnType("int");

                    b.HasKey("BlogPostId", "TagId");

                    b.HasIndex("TagId");

                    b.HasIndex("BlogPostTagBlogPostId", "BlogPostTagTagId");

                    b.ToTable("BlogPostsTags");

                    b.HasComment("PostTag entity");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Cart item identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("CustummerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Custummer identifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("Product identifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Quantity of a product");

                    b.HasKey("Id");

                    b.HasIndex("CustummerId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");

                    b.HasComment("Cart with item");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Category identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Animal type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Category description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Categiry name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasComment("Product Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalType = "Куче",
                            Description = "Висококачествена суха храна за кучета от различни породи и възрасти.",
                            Name = "Суха храна"
                        },
                        new
                        {
                            Id = 2,
                            AnimalType = "Куче",
                            Description = "Висококачествена консервирана храна за кучета, богата на месо и протеини.",
                            Name = "Консервирана храна"
                        },
                        new
                        {
                            Id = 3,
                            AnimalType = "Куче",
                            Description = "Вкусни и здравословни лакомства за награждаване и обучение на кучета.",
                            Name = "Лакомства за награда"
                        },
                        new
                        {
                            Id = 4,
                            AnimalType = "Куче",
                            Description = "Висококачествени хранителни добавки и витамини за подобряване на здравето на кучетата.",
                            Name = "Хранителни добавки и витамини"
                        },
                        new
                        {
                            Id = 5,
                            AnimalType = "Куче",
                            Description = "Разнообразни аксесоари за кучета, включително играчки, легла, нашийници и каишки.",
                            Name = "Аксесоари"
                        });
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Comment identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BlogPostId")
                        .HasColumnType("int")
                        .HasComment("BlogPost identifier");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2")
                        .HasComment("Comment creation date");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Comment content");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasComment("Product identifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User identifier");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasComment("User comment");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Order identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasComment("Order is completed or not");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date time of order");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Total price of order");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User identifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasComment("Order of product/s");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.OrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Order details identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasComment("Order identifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price for a unit of product");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("Product identifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Quantity of units");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrdersDetails");

                    b.HasComment("Details of the order");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Product identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasComment("Animal type");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasComment("Category identifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Product image path");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Product long description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Product name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Product price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Product quantity in store");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Product short description");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasComment("Animal product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalType = "Куче",
                            CategoryId = 1,
                            ImageUrl = "~/Images/Products/Dogs/DryFoods/Royal_Canin_Adult.jpg",
                            LongDescription = "Royal Canin Adult е специално разработена суха храна за възрастни кучета от средни породи (11-25 кг). Тя съдържа оптимален баланс от хранителни вещества, включително високо качествени протеини, за поддържане на здрава мускулна маса, и специфични хранителни вещества за поддържане на здравето на кожата и козината. Храната също така подпомага здравето на зъбите и венците чрез включването на хрупкави гранули, които помагат за намаляване на натрупването на зъбен камък.",
                            Name = "Royal Canin Adult",
                            Price = 32.99m,
                            Quantity = 500,
                            ShortDescription = "Пълноценна суха храна за възрастни кучета от средни породи."
                        },
                        new
                        {
                            Id = 2,
                            AnimalType = "Куче",
                            CategoryId = 1,
                            ImageUrl = "~/Images/Products/Dogs/DryFoods/Hills_Science_Plan_Puppy.jpg",
                            LongDescription = "Hill's Science Plan Puppy е висококачествена суха храна, специално разработена за подрастващи кученца. Тя съдържа точния баланс от хранителни вещества, необходими за здравословен растеж и развитие, включително високо качествени протеини за изграждане на силни мускули, и DHA от рибено масло за подпомагане на здравето на мозъка и зрението. Храната е лесносмилаема и съдържа балансирано съотношение на калций и фосфор за здрави кости и зъби.",
                            Name = "Hill's Science Plan Puppy",
                            Price = 28.99m,
                            Quantity = 500,
                            ShortDescription = "Специално разработена суха храна за подрастващи кученца."
                        },
                        new
                        {
                            Id = 3,
                            AnimalType = "Куче",
                            CategoryId = 1,
                            ImageUrl = "~/Images/Products/Dogs/DryFoods/Purina_Pro_Plan_Adult_Dog.jpg",
                            LongDescription = "Purina Pro Plan Adult е висококачествена суха храна, специално разработена за активни възрастни кучета. Тя съдържа високо качествени протеини от пиле като основна съставка, за поддържане на здрава мускулна маса, и оптимален баланс от хранителни вещества за цялостно здраве и жизненост. Храната включва и специфични хранителни вещества за поддържане на здравето на сърцето, както и омега-3 мастни киселини за здрава кожа и козина.",
                            Name = "Purina Pro Plan Adult",
                            Price = 39.99m,
                            Quantity = 500,
                            ShortDescription = "Висококачествена суха храна за активни възрастни кучета."
                        },
                        new
                        {
                            Id = 4,
                            AnimalType = "Куче",
                            CategoryId = 1,
                            ImageUrl = "~/Images/Products/Dogs/DryFoods/Arcana_Wild_Pairie_Adult_Dog.jpg",
                            LongDescription = "Acana Wild Prairie е висококачествена суха храна за кучета от всички възрасти, с високо съдържание на месо. Тя съдържа 70% месо, включително пиле, пуйка, риба и яйца, които осигуряват богат източник на протеини за изграждане и поддържане на здрава мускулна маса. Храната включва и разнообразие от плодове, зеленчуци и билки, които предоставят естествени източници на антиоксиданти, витамини и минерали. Не съдържа зърнени продукти, изкуствени добавки или консерванти.",
                            Name = "Acana Wild Prairie",
                            Price = 49.99m,
                            Quantity = 500,
                            ShortDescription = "Суха храна с високо съдържание на месо за кучета от всички възрасти."
                        },
                        new
                        {
                            Id = 5,
                            AnimalType = "Куче",
                            CategoryId = 1,
                            ImageUrl = "~/Images/Products/Dogs/DryFoods/ORIJEN_Six_Fish Dry_Dog_Food.jpg",
                            LongDescription = "Orijen Six Fish е висококачествена суха храна за кучета от всички възрасти, съдържаща шест вида прясна риба - сьомга, херинга, бяла риба, скумрия, американска менхадена и сардини. Тази богата на протеини и омега-3 мастни киселини храна подпомага здравето на кожата и козината, както и цялостното здраве и жизненост на кучетата. Не съдържа зърнени продукти, изкуствени добавки или консерванти, а само висококачествени, натурални съставки.",
                            Name = "Orijen Six Fish",
                            Price = 54.99m,
                            Quantity = 500,
                            ShortDescription = "Суха храна за кучета с шест вида прясна риба."
                        },
                        new
                        {
                            Id = 6,
                            AnimalType = "Куче",
                            CategoryId = 2,
                            ImageUrl = "~/Images/Products/Dogs/WetFoods/Royal_Canin_Wet_Good.jpg",
                            LongDescription = "Royal Canin Wet Food е висококачествена консервирана храна, специално разработена за поддържане на оптимално здраве и жизненост при кучетата. Произведена от внимателно подбрани съставки, включително високо качествени протеини, тази храна осигурява балансирано хранене и отличен вкус. Меката и сочна текстура я прави лесна за дъвчене и поглъщане, дори за кучета с чувствителни зъби или венци. Съдържа и добавени витамини и минерали за цялостно здраве. Предлага се в различни вкусове, за да задоволи предпочитанията на всяко куче.",
                            Name = "Royal Canin Wet Food",
                            Price = 2.49m,
                            Quantity = 500,
                            ShortDescription = "Меки хапки в сос за възрастни кучета от малки породи."
                        },
                        new
                        {
                            Id = 7,
                            AnimalType = "Куче",
                            CategoryId = 2,
                            ImageUrl = "~/Images/Products/Dogs/WetFoods/Hills_Science_Diet_Wet_Food.jpg",
                            LongDescription = "Hill's Science Diet Wet Food е научно разработена консервирана храна, предназначена да осигури оптимално хранене за кучета във всеки етап от живота. Формулирана от ветеринарни диетолози, тази храна съдържа висококачествени протеини за поддържане на здрави мускули, балансирани мазнини за енергия и основни витамини и минерали за цялостно здраве. Меката текстура и апетитният аромат я правят привлекателна дори за най-капризните кучета. Предлага се в различни формули, пригодени за специфичните хранителни нужди на кучета от различни възрасти, размери и породи. Идеална за самостоятелно хранене или като допълнение към суха храна Hill's Science Diet.",
                            Name = "Hill's Science Plan Wet Food",
                            Price = 2.99m,
                            Quantity = 500,
                            ShortDescription = "Балансирана консервирана храна за кучета с чувствителна кожа."
                        },
                        new
                        {
                            Id = 8,
                            AnimalType = "Куче",
                            CategoryId = 2,
                            ImageUrl = "~/Images/Products/Dogs/WetFoods/Purina_ONE_SmartBlend.jpg",
                            LongDescription = "Purina ONE SmartBlend е висококачествена консервирана храна, предназначена да осигури цялостно и балансирано хранене за вашето куче. Приготвена от внимателно подбрани съставки, включително истинско месо като основен протеин, тази храна подкрепя здравето на мускулите и жизнеността. Съдържа и сложни въглехидрати за енергия, както и основни витамини и минерали за поддържане на имунната система. Меката и сочна текстура, комбинирана с апетитен аромат, гарантира, че вашето куче ще се наслаждава на всяко хранене. Подходяща за самостоятелно хранене или като допълнение към суха храна.",
                            Name = "Purina Pro Plan Wet Food",
                            Price = 2.79m,
                            Quantity = 500,
                            ShortDescription = "Консервирана храна с пиле и ориз за възрастни кучета."
                        },
                        new
                        {
                            Id = 9,
                            AnimalType = "Куче",
                            CategoryId = 2,
                            ImageUrl = "~/Images/Products/Dogs/WetFoods/Pedigree_Chopped_Ground_Food.jpg",
                            LongDescription = "Pedigree Chopped Ground Dinner е питателна и вкусна консервирана храна за кучета, приготвена с висококачествени съставки, включително истинско месо. Нарязаните парченца във вкусен сос осигуряват привлекателна текстура и аромат, които кучетата обожават. Тази балансирана формула съдържа оптимално съотношение на протеини, мазнини и въглехидрати за поддържане на здравето и енергията на вашето куче. Обогатена е с основни витамини и минерали за подкрепа на имунната система и цялостното здраве. Лесна за сервиране и перфектна като самостоятелно хранене или като добавка към суха храна.",
                            Name = "Pedigree Chopped Ground Dinner",
                            Price = 1.99m,
                            Quantity = 500,
                            ShortDescription = "Питателна и вкусна консервирана храна с истинско месо."
                        },
                        new
                        {
                            Id = 10,
                            AnimalType = "Куче",
                            CategoryId = 2,
                            ImageUrl = "~/Images/Products/Dogs/WetFoods/CESAR_Adult_Wet_Dog_Food.jpg",
                            LongDescription = "Cesar Classic Loaf in Sauce е премиум консервирана храна за кучета, приготвена с внимателно подбрани съставки за изключителен вкус и хранителна стойност. Класическото руло в апетитен сос е изкусително ястие, на което никое куче не може да устои. Произведена от висококачествени протеини, включително истинско месо, тази храна осигурява балансирано и пълноценно хранене. Меката текстура я прави подходяща дори за кучета с чувствителни зъби или венци. Предлага се в различни вкусове, вдъхновени от човешката кухня, за разнообразие и удоволствие при всяко хранене.",
                            Name = "Cesar Classic Loaf in Sauce",
                            Price = 2.49m,
                            Quantity = 500,
                            ShortDescription = "Премиум консервирана храна с изключителен вкус."
                        },
                        new
                        {
                            Id = 11,
                            AnimalType = "Куче",
                            CategoryId = 3,
                            ImageUrl = "~/Images/Products/Dogs/Treats/Zukes_Mini_Naturals_Dog.jpg",
                            LongDescription = "Zuke's Mini Naturals са вкусни и хранителни лакомства, приготвени от висококачествени, натурални съставки. Тези меки хапки са богати на протеини от истинско месо и не съдържат изкуствени добавки, царевица, соя или пшеница. Малкият им размер ги прави идеални за тренировка или като здравословна награда. Предлагат се в различни вкусове, включително пиле, заек и патица, за да задоволят вкусовите предпочитания на всяко куче. Zuke's Mini Naturals са чудесен избор за собственици, които търсят питателни и вкусни лакомства за своите кучета.",
                            Name = "Zuke's Mini Naturals",
                            Price = 4.99m,
                            Quantity = 500,
                            ShortDescription = "Натурални лакомства без изкуствени добавки."
                        },
                        new
                        {
                            Id = 12,
                            AnimalType = "Куче",
                            CategoryId = 3,
                            ImageUrl = "~/Images/Products/Dogs/Treats/Blue_Buffalo_Wilderness_Trail_Treats.jpg",
                            LongDescription = "Blue Buffalo Wilderness Treats са високопротеинови лакомства, вдъхновени от естествената диета на вълците. Приготвени с истински дивеч като главна съставка, тези лакомства осигуряват хранителна доза протеини за поддържане на силни мускули и енергични нива. Те не съдържат изкуствени аромати, оцветители или консерванти, което ги прави чудесен избор за кучета с чувствителни стомаси. Хрупкавата текстура помага за премахване на зъбната плака и поддържане на здрави зъби. Blue Buffalo Wilderness Treats са перфектни за активни кучета, нуждаещи се от питателна закуска между храненията.",
                            Name = "Blue Buffalo Wilderness Treats",
                            Price = 6.99m,
                            Quantity = 500,
                            ShortDescription = "Лакомства с високо съдържание на протеини за активни кучета."
                        },
                        new
                        {
                            Id = 13,
                            AnimalType = "Куче",
                            CategoryId = 3,
                            ImageUrl = "~/Images/Products/Dogs/Treats/Greenies_Original_Dog_Dental_Chew.jpg",
                            LongDescription = "Greenies Dental Chews са клинично доказани лакомства за грижа за зъбите, които помагат за намаляване на зъбната плака и зъбния камък. Техният уникален текстура и форма осигуряват почистващо действие, което достига до задните зъби и е трудно достъпно с традиционното четкане. Приготвени от висококачествени, лесносмилаеми съставки, тези лакомства са хранителни и лесни за смилане. Препоръчват се от ветеринари за ежедневна употреба като част от цялостната дентална грижа. Greenies Dental Chews са достъпни в различни размери, за да отговарят на нуждите на кучета от всички породи.",
                            Name = "Greenies Dental Chews",
                            Price = 8.99m,
                            Quantity = 500,
                            ShortDescription = "Лакомства за дентална грижа, препоръчани от ветеринари."
                        },
                        new
                        {
                            Id = 14,
                            AnimalType = "Куче",
                            CategoryId = 3,
                            ImageUrl = "~/Images/Products/Dogs/Treats/Pup-Peroni_Original_Lean_Beef_Flavor.jpg",
                            LongDescription = "Pup-Peroni Original Beef Flavor са вкусни лакомства със завладяващ аромат на говеждо, на който кучетата не могат да устоят. Приготвени от истинско говеждо като основна съставка, тези меки хапки имат привлекателна текстура, която ги прави перфектни за тренировки или просто за глезене. Не съдържат изкуствени аромати или оцветители и са обогатени с витамини и минерали за поддържане на цялостното здраве. Малкият им размер ги прави идеални за кучета от всякакъв размер. Pup-Peroni Original Beef Flavor са чудесен начин да наградите вашето куче и да укрепите връзката помежду ви.",
                            Name = "Pup-Peroni Original Beef Flavor",
                            Price = 3.99m,
                            Quantity = 500,
                            ShortDescription = "Ароматни лакомства с говеждо за максимална наслада."
                        },
                        new
                        {
                            Id = 15,
                            AnimalType = "Куче",
                            CategoryId = 3,
                            ImageUrl = "~/Images/Products/Dogs/Treats/Wellness_Soft_Puppy_Bites.jpg",
                            LongDescription = "Wellness Soft Puppy Bites са специално разработени лакомства за растящите нужди на кученцата. Произведени от внимателно подбрани, натурални съставки, включително истинско месо от заек и сьомга, тези меки хапки осигуряват висококачествени протеини за здрави мускули и DHA за подкрепа на мозъчното развитие. Обогатени са с витамини и минерали за цялостно здраве и не съдържат изкуствени оцветители, аромати или консерванти. Нежната им текстура ги прави лесни за дъвчене и поглъщане от малките усти. Wellness Soft Puppy Bites са перфектното лакомство за тренировка и награждаване на вашето малко кученце.",
                            Name = "Wellness Soft Puppy Bites",
                            Price = 5.99m,
                            Quantity = 500,
                            ShortDescription = "Нежни лакомства с натурални съставки за кученца."
                        },
                        new
                        {
                            Id = 16,
                            AnimalType = "Куче",
                            CategoryId = 4,
                            ImageUrl = "~/Images/Products/Dogs/SupplementsVitamins/nuvet_plus.jpg",
                            LongDescription = "NuVet Plus All-in-One Supplement е висококачествена хранителна добавка, разработена за поддържане на цялостното здраве и жизненост на кучетата. Тази мощна формула съдържа внимателно подбрана комбинация от витамини, минерали, антиоксиданти и билки, които работят синергично за подкрепа на имунната система, ставите, храносмилането и козината. Произведена от висококачествени, натурални съставки, тази добавка не съдържа изкуствени консерванти, оцветители или аромати. Подходяща за кучета от всички възрасти и породи, NuVet Plus е чудесен начин да осигурите на вашия домашен любимец оптимално здраве и дълголетие.",
                            Name = "NuVet Plus All-in-One Supplement",
                            Price = 39.99m,
                            Quantity = 500,
                            ShortDescription = "Пълноценна добавка за цялостно здраве и жизненост."
                        },
                        new
                        {
                            Id = 17,
                            AnimalType = "Куче",
                            CategoryId = 4,
                            ImageUrl = "~/Images/Products/Dogs/SupplementsVitamins/Zesty_Paws_Multivitamin.jpg",
                            LongDescription = "Zesty Paws Multivitamin Treats са вкусни и питателни лакомства, обогатени с основни витамини и минерали за ежедневна подкрепа на здравето. Тези меки хапки съдържат комплекс от витамини от група B за енергийно ниво и метаболизъм, витамин Е за здрава кожа и козина, и витамин С за укрепване на имунната система. Обогатени са и с минерали като цинк, биотин и фолиева киселина за цялостно здраве. Приготвени от висококачествени, натурални съставки, тези лакомства не съдържат изкуствени консерванти, оцветители или аромати. Zesty Paws Multivitamin Treats са вкусен и удобен начин да осигурите на вашето куче необходимите хранителни вещества за оптимално здраве.",
                            Name = "Zesty Paws Multivitamin Treats",
                            Price = 24.99m,
                            Quantity = 500,
                            ShortDescription = "Вкусни мултивитаминни лакомства за ежедневна подкрепа."
                        },
                        new
                        {
                            Id = 18,
                            AnimalType = "Куче",
                            CategoryId = 4,
                            ImageUrl = "~/Images/Products/Dogs/SupplementsVitamins/Pet_Honesty_Omega-3_Oil.jpg",
                            LongDescription = "PetHonesty Omega-3 Fish Oil е висококачествена добавка, осигуряваща чисти и концентрирани омега-3 мастни киселини от дива риба. Тези есенциални мастни киселини подпомагат здравето на кожата и козината, подкрепят мозъчната функция и зрението, и спомагат за облекчаване на възпаленията. Произведен от устойчиви източници и молекулярно дестилиран за премахване на тежки метали и други замърсители, този рибен омега-3 е безопасен и ефективен. Лесно се добавя към храната на вашето куче за ежедневна подкрепа. PetHonesty Omega-3 Fish Oil е чудесен избор за собственици, които търсят висококачествена добавка за поддържане на оптималното здраве на своите домашни любимци.",
                            Name = "PetHonesty Omega-3 Fish Oil",
                            Price = 19.99m,
                            Quantity = 500,
                            ShortDescription = "Чист рибен омега-3 за здрава кожа, козина и мозък."
                        },
                        new
                        {
                            Id = 19,
                            AnimalType = "Куче",
                            CategoryId = 4,
                            ImageUrl = "~/Images/Products/Dogs/SupplementsVitamins/VetriScience_GlycoFlex.jpg",
                            LongDescription = "VetriScience Laboratories GlycoFlex Joint Support е клинично доказана добавка за подпомагане на здравето на ставите при кучета от всички възрасти и породи. Тази мощна формула съдържа глюкозамин, хондроитин и MSM, които работят заедно за подкрепа на хрущялната функция, облекчаване на възпаленията и подобряване на подвижността. Обогатена е с мангански аскорбат за стимулиране на производството на хрущял и зелени миди от Нова Зеландия за допълнителни противовъзпалителни ползи. Подходяща за ежедневна употреба, тази добавка е особено полезна за по-възрастни кучета, едри породи и работни кучета. VetriScience Laboratories GlycoFlex Joint Support е надежден избор за поддържане на здравето и комфорта на ставите на вашето куче през целия му живот.",
                            Name = "VetriScience Laboratories GlycoFlex Joint Support",
                            Price = 29.99m,
                            Quantity = 500,
                            ShortDescription = "Клинично доказана формула за здраве на ставите."
                        },
                        new
                        {
                            Id = 20,
                            AnimalType = "Куче",
                            CategoryId = 4,
                            ImageUrl = "~/Images/Products/Dogs/SupplementsVitamins/Purina_Pro_Plan_Fortiflora.jpg",
                            LongDescription = "Purina Pro Plan Veterinary Diets FortiFlora Probiotic е пробиотична добавка, специално разработена за подкрепа на храносмилателното здраве при кучета. Тази мощна формула съдържа живи, активни култури от бактерии, които спомагат за възстановяване на баланса на чревната микрофлора и укрепване на имунната система. Доказано е, че помага при храносмилателен дискомфорт, диария и стомашно-чревни разстройства. Лесно се добавя към храната и е подходяща за ежедневна употреба. Препоръчва се от ветеринари за кучета, които се възстановяват от заболяване или преминават през стресиращи ситуации. Purina Pro Plan Veterinary Diets FortiFlora Probiotic е надежден избор за поддържане на оптималното храносмилателно здраве на вашето куче.",
                            Name = "Purina Pro Plan Veterinary Diets FortiFlora Probiotic",
                            Price = 34.99m,
                            Quantity = 500,
                            ShortDescription = "Мощен пробиотик за подкрепа на храносмилателното здраве."
                        },
                        new
                        {
                            Id = 21,
                            AnimalType = "Куче",
                            CategoryId = 5,
                            ImageUrl = "~/Images/Products/Dogs/Аccessories/KONG_Classic_Dog_Toy.jpg",
                            LongDescription = "Класическата играчка Kong, изработена от здрава гума, която е идеална за дъвчене и игра. Може да се напълни с лакомства за допълнително забавление и стимулация.",
                            Name = "Kong Classic",
                            Price = 12.99m,
                            Quantity = 500,
                            ShortDescription = "Класическа играчка Kong за дъвчене и игра."
                        },
                        new
                        {
                            Id = 22,
                            AnimalType = "Куче",
                            CategoryId = 5,
                            ImageUrl = "~/Images/Products/Dogs/Аccessories/Furhaven_Orthopedic_Dog_Bed.jpg",
                            LongDescription = "Висококачествено ортопедично легло за кучета, с мемори пяна, която осигурява комфорт и поддръжка на ставите. Подходящо за кучета от всички възрасти и породи.",
                            Name = "FurHaven Orthopedic Dog Bed",
                            Price = 49.99m,
                            Quantity = 500,
                            ShortDescription = "Ортопедично легло за кучета с мемори пяна."
                        },
                        new
                        {
                            Id = 23,
                            AnimalType = "Куче",
                            CategoryId = 5,
                            ImageUrl = "~/Images/Products/Dogs/Аccessories/Ruffwear_Front_Range_Dog_Harness.jpg",
                            LongDescription = "Удобен и здрав нагръдник за кучета, с подплатени презрамки и лесно закопчаване. Идеален за разходки и приключения на открито.",
                            Name = "Ruffwear Front Range Harness",
                            Price = 39.99m,
                            Quantity = 500,
                            ShortDescription = "Удобен и здрав нагръдник за кучета."
                        },
                        new
                        {
                            Id = 24,
                            AnimalType = "Куче",
                            CategoryId = 5,
                            ImageUrl = "~/Images/Products/Dogs/Аccessories/Chuckit!_Ultra_Ball.jpg",
                            LongDescription = "Издръжлива топка за игра и апортиране, изработена от здрав материал, който издържа на агресивно дъвчене. Подходяща за игра на открито и в парка.",
                            Name = "Chuckit! Ultra Ball",
                            Price = 9.99m,
                            Quantity = 500,
                            ShortDescription = "Издръжлива топка за игра и апортиране."
                        },
                        new
                        {
                            Id = 25,
                            AnimalType = "Куче",
                            CategoryId = 5,
                            ImageUrl = "~/Images/Products/Dogs/Аccessories/Nylabone_Dura_Chew.jpg",
                            LongDescription = "Здрава играчка за дъвчене, специално разработена за кучета, които обичат да дъвчат агресивно. Помага за поддържане на здрави зъби и венци, като същевременно предотвратява скуката.",
                            Name = "Nylabone Dura Chew",
                            Price = 8.99m,
                            Quantity = 500,
                            ShortDescription = "Здрава играчка за дъвчене, подходяща за агресивни дъвкачи."
                        });
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Tag identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Tag name");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasComment("Tag entity");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int")
                        .HasComment("Address identifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContactPreferance")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("User's first name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("User's last name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Recipient name");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("98cdd9b2-8c6a-49de-92e0-a1a997d1468e"),
                            AccessFailedCount = 0,
                            AddressId = 1,
                            ConcurrencyStamp = "63e48b0a-6256-4bc9-96ef-e694520e050f",
                            ContactPreferance = 0,
                            Email = "jordan4.71@abv.bg",
                            EmailConfirmed = false,
                            FirstName = "Yordan",
                            LastName = "Ivanov",
                            LockoutEnabled = false,
                            NormalizedEmail = "JORDAN4.71@ABV.BG",
                            NormalizedUserName = "IVANOV",
                            PasswordHash = "AQAAAAEAACcQAAAAEJtOvGtSQ/u238/dLSuJdLvlZKBA23m4elIdlm1iDOPRJbuEcAlNFlaGkUml0a6kCQ==",
                            PhoneNumberConfirmed = false,
                            RecipientName = "",
                            TwoFactorEnabled = false,
                            UserName = "Ivanov"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PetShopProject.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PetShopProject.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetShopProject.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PetShopProject.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.BlogPost", b =>
                {
                    b.HasOne("PetShopProject.Infrastructure.Data.Models.User", "Author")
                        .WithMany("BlogPosts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.BlogPostTag", b =>
                {
                    b.HasOne("PetShopProject.Infrastructure.Data.Models.BlogPost", "BlogPost")
                        .WithMany("BlogPostsTags")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetShopProject.Infrastructure.Data.Models.Tag", "Tag")
                        .WithMany("BlogPostsTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetShopProject.Infrastructure.Data.Models.BlogPostTag", null)
                        .WithMany("BlogPostsTags")
                        .HasForeignKey("BlogPostTagBlogPostId", "BlogPostTagTagId");

                    b.Navigation("BlogPost");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.CartItem", b =>
                {
                    b.HasOne("PetShopProject.Infrastructure.Data.Models.User", "Custummer")
                        .WithMany("CartItems")
                        .HasForeignKey("CustummerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetShopProject.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Custummer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.Comment", b =>
                {
                    b.HasOne("PetShopProject.Infrastructure.Data.Models.BlogPost", "BlogPost")
                        .WithMany("Comments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PetShopProject.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PetShopProject.Infrastructure.Data.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("PetShopProject.Infrastructure.Data.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.OrderDetails", b =>
                {
                    b.HasOne("PetShopProject.Infrastructure.Data.Models.Order", "Order")
                        .WithMany("OrdersDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetShopProject.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("OrdersDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.Product", b =>
                {
                    b.HasOne("PetShopProject.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.User", b =>
                {
                    b.HasOne("PetShopProject.Infrastructure.Data.Models.Address", "Address")
                        .WithOne("User")
                        .HasForeignKey("PetShopProject.Infrastructure.Data.Models.User", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.Address", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.BlogPost", b =>
                {
                    b.Navigation("BlogPostsTags");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.BlogPostTag", b =>
                {
                    b.Navigation("BlogPostsTags");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.Order", b =>
                {
                    b.Navigation("OrdersDetails");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.Product", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("OrdersDetails");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.Tag", b =>
                {
                    b.Navigation("BlogPostsTags");
                });

            modelBuilder.Entity("PetShopProject.Infrastructure.Data.Models.User", b =>
                {
                    b.Navigation("BlogPosts");

                    b.Navigation("CartItems");

                    b.Navigation("Comments");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
